(() => {
    'use strict';

    const MAX_INT_DIGITS = 4;
    const MAX_FRACTION_DIGITS = 4;
    const DIVISION_DECIMALS = 10;
    const HOLD_TO_COPY_MS = 1500;
    const FLASH_MS = 1500;
    const SCALE_FACTOR = 10n ** BigInt(MAX_FRACTION_DIGITS);
    const DIVISION_FACTOR = 10n ** BigInt(DIVISION_DECIMALS);
    const DECIMAL_PATTERN = /^(-?)(\d*)(?:\.(\d*))?$/;
    const BLOCKED_KEYS = new Set(['e', 'E', '+']);
    const byId = (id) => document.getElementById(id);
    const inputs = [byId('num1'), byId('num2')];
    const operatorRow = byId('operators');
    const operatorButtons = [...operatorRow.querySelectorAll('.operator-button')];
    const equalsButton = byId('equals');
    const resultBox = byId('result');
    const resultText = byId('resultText');
    const reduceMotion = matchMedia('(prefers-reduced-motion: reduce)');
    const state = { operator: '+', holdTimer: 0, flashTimer: 0 };
    const OPERATIONS = {'+':(a,b)=>({value:a+b,decimals:MAX_FRACTION_DIGITS}),'-':(a,b)=>({value:a-b,decimals:MAX_FRACTION_DIGITS}),'*':(a,b)=>({value:a*b,decimals:MAX_FRACTION_DIGITS*2}),'/':divide};

    function divide(a,b){const negative=(a<0n)!==(b<0n);const absA=a<0n?-a:a;const absB=b<0n?-b:b;const numerator=absA*DIVISION_FACTOR;let quotient=numerator/absB;if(2n*(numerator%absB)>=absB)quotient+=1n;return{value:negative?-quotient:quotient,decimals:DIVISION_DECIMALS};}
    function parseDecimal(text){const match=DECIMAL_PATTERN.exec(text);if(!match)return null;const[,sign,whole='',fraction='']=match;if(!whole&&!fraction)return null;const scaled=BigInt(whole||'0')*SCALE_FACTOR+BigInt((fraction+'0'.repeat(MAX_FRACTION_DIGITS)).slice(0,MAX_FRACTION_DIGITS));return sign==='-'?-scaled:scaled;}
    function formatDecimal(result){const negative=result.value<0n;const digits=(negative?-result.value:result.value).toString().padStart(result.decimals+1,'0');const whole=digits.slice(0,digits.length-result.decimals);const fraction=digits.slice(digits.length-result.decimals).replace(/0+$/,'');return(negative?'-':'')+whole+(fraction?'.'+fraction:'');}
    function limitDigits(input){const match=DECIMAL_PATTERN.exec(input.value);if(!match)return;const[,sign,whole='',fraction='']=match;if(whole.length<=MAX_INT_DIGITS&&fraction.length<=MAX_FRACTION_DIGITS)return;const limitedWhole=whole.slice(0,MAX_INT_DIGITS);const limitedFraction=fraction.slice(0,MAX_FRACTION_DIGITS);input.value=sign+(limitedWhole||(limitedFraction?'0':''))+(limitedFraction?'.'+limitedFraction:'');}
    function animate(element,preset){if(reduceMotion.matches||!element.animate)return;const frames={press:[{transform:'scale(1)'},{transform:'scale(.93)',offset:.5},{transform:'scale(1)'}],pop:[{transform:'scale(.96)',opacity:.35},{transform:'scale(1)',opacity:1}],shake:[{transform:'translateX(0)'},{transform:'translateX(-6px)',offset:.2},{transform:'translateX(6px)',offset:.4},{transform:'translateX(-6px)',offset:.6},{transform:'translateX(6px)',offset:.8},{transform:'translateX(0)'}],flash:[{opacity:.2},{opacity:1}],switch:[{transform:'scale(1)'},{transform:'scale(1.07)',offset:.45},{transform:'scale(1)'}]};element.animate(frames[preset],{duration:preset==='shake'?420:preset==='pop'?260:preset==='press'?130:300,easing:'cubic-bezier(.22,1,.36,1)'});}
    function buzz(ms){try{if(!reduceMotion.matches&&navigator.vibrate)navigator.vibrate(ms);}catch{}}
    let blobCount = -1;
    function getBlobCount(){const width=window.innerWidth,height=window.innerHeight,area=width*height;if(width<280||height<280)return 0;if(area<250000)return 2;if(area<600000)return 3;if(area<1200000)return 5;if(area<2500000)return 7;if(area<5000000)return 10;return 14;}
    function scatterBlobs(){const count=getBlobCount();if(count===blobCount)return;blobCount=count;const tones=[['255, 149, 0',.15],['255, 95, 46',.11],['255, 200, 110',.09]];document.querySelectorAll('.blob').forEach((blob,index)=>{blob.style.display=index<count?'block':'none';if(index>=count)return;const size=24+Math.random()*22;const tone=tones[index%tones.length];const sideX=index%2?'right':'left';const sideY=index%4>1?'bottom':'top';blob.style.width=size+'vmax';blob.style.height=size+'vmax';blob.style[sideX]=(-size*(.2+Math.random()*.35))+'vmax';blob.style[sideY]=(-size*(.2+Math.random()*.35))+'vmax';blob.style.background=`radial-gradient(closest-side,rgba(${tone[0]},${tone[1]}),rgba(${tone[0]},${(tone[1]*.4).toFixed(3)}) 45%,transparent 72%)`;blob.style.setProperty('--dx',(Math.random()*18-9)+'vmax');blob.style.setProperty('--dy',(Math.random()*18-9)+'vmax');blob.style.setProperty('--sc',(1.04+Math.random()*.12).toFixed(2));blob.style.animationDuration=Math.round(48+Math.random()*34)+'s';blob.style.animationDelay='-'+Math.round(Math.random()*40)+'s';});}
    let audioContext=null;function chime(type){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx||reduceMotion.matches)return;if(!audioContext)audioContext=new Ctx();if(audioContext.state==='suspended')audioContext.resume();const notes={tick:[1320,1080,.06],hold:[440,660,.12],pop:[523.25,783.99,.18],error:[196,110,.24],copied:[659.25,987.77,.2]}[type];if(!notes)return;const[start,end,length]=notes;const now=audioContext.currentTime;const osc=audioContext.createOscillator();const gain=audioContext.createGain();osc.type=type==='error'?'square':'sine';osc.frequency.setValueAtTime(start,now);osc.frequency.exponentialRampToValueAtTime(end,now+length);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.05,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+length);osc.connect(gain);gain.connect(audioContext.destination);osc.start(now);osc.stop(now+length);}
    function fitResultText(){const styles=getComputedStyle(resultBox);const available=resultBox.clientWidth-parseFloat(styles.paddingLeft)-parseFloat(styles.paddingRight);const natural=resultText.scrollWidth;const scale=available>0&&natural>available?available/natural:1;resultText.style.transform=scale<1?'scale('+scale.toFixed(4)+')':'';}
    let fitFrame=0;function scheduleFit(){if(fitFrame)return;fitFrame=requestAnimationFrame(()=>{fitFrame=0;fitResultText();});}
    function render(text,preset){clearTimeout(state.flashTimer);resultText.textContent=text;scheduleFit();if(preset)animate(resultBox,preset);}
    function flash(message){const original=resultText.textContent;render(message,'flash');state.flashTimer=setTimeout(()=>render(original,'flash'),FLASH_MS);}
    function setOperator(button){if(state.operator===button.dataset.op)return;state.operator=button.dataset.op;operatorButtons.forEach(candidate=>{const active=candidate===button;candidate.classList.toggle('active',active);candidate.setAttribute('aria-pressed',String(active));});animate(button,'switch');buzz(8);chime('tick');}
    function calculate(){animate(equalsButton,'press');buzz(10);const[a,b]=inputs.map(input=>parseDecimal(input.value));if(a===null||b===null){render('Error','shake');chime('error');return}if(state.operator==='/'&&b===0n){if(a===0n){render('Error','shake');chime('error');return}render(a>0n?'Infinity':'-Infinity','pop');chime('pop');return}render(formatDecimal(OPERATIONS[state.operator](a,b)),'pop');chime('pop');}
    function fallbackCopy(text){const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();area.setSelectionRange(0,text.length);let copied=false;try{copied=document.execCommand('copy')}catch{}area.remove();return copied;}
    async function copyResult(){const text=resultText.textContent;if(['Copied!','Copy failed','Error'].includes(text))return;cancelHold();let copied=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);copied=true}else{copied=fallbackCopy(text)}}catch{copied=fallbackCopy(text)}if(copied){flash('Copied!');buzz(14);chime('copied')}else{flash('Copy failed');chime('error')}}
    function startHold(){cancelHold();resultBox.classList.add('holding');chime('hold');state.holdTimer=setTimeout(copyResult,HOLD_TO_COPY_MS)}function cancelHold(){clearTimeout(state.holdTimer);resultBox.classList.remove('holding')}
    function keySound(event,input){if(event.data==='.')return;if(/^\d$/.test(event.data||''))chime('tick');}
    inputs.forEach(input=>{input.addEventListener('input',event=>{limitDigits(input);render('0');keySound(event,input)});input.addEventListener('keydown',event=>{if(event.key==='Enter')calculate();if(BLOCKED_KEYS.has(event.key))event.preventDefault()});input.addEventListener('wheel',event=>{if(document.activeElement===input)event.preventDefault()},{passive:false})});
    operatorRow.addEventListener('click',event=>{const button=event.target.closest('.operator-button');if(button)setOperator(button)});equalsButton.addEventListener('click',calculate);resultBox.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;startHold()});['pointerup','pointercancel','pointerleave'].forEach(type=>resultBox.addEventListener(type,cancelHold));resultBox.addEventListener('animationend',event=>{if(event.animationName==='hold-fill'&&resultBox.classList.contains('holding'))copyResult()});window.addEventListener('blur',cancelHold);resultBox.addEventListener('contextmenu',event=>event.preventDefault());resultBox.addEventListener('dragstart',event=>event.preventDefault());
    if('ResizeObserver'in window)new ResizeObserver(scheduleFit).observe(resultBox);window.addEventListener('resize',()=>{scheduleFit();scatterBlobs()},{passive:true});scatterBlobs();scheduleFit();
})();
